# Generated by Django 4.0.6 on 2022-10-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('BookingID', models.AutoField(primary_key=True, serialize=False)),
                ('TableID', models.IntegerField()),
                ('BookDateTime', models.DateTimeField()),
                ('BookDuration', models.CharField(choices=[('2', '2 hours'), ('3', '3 hours'), ('4', '4 hours')], default=2, max_length=255)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tables',
            constraint=models.CheckConstraint(check=models.Q(('TableID__gte', 1), ('TableID__lt', 20)), name='A TableID value is valid between 1 and 50'),
        ),
        migrations.AlterUniqueTogether(
            name='tables',
            unique_together={('TableID', 'BookDateTime')},
        ),
    ]
