# Generated by Django 4.0.6 on 2022-10-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='BookDuration',
            field=models.CharField(default='2 hours', max_length=255),
        ),
    ]
