# Generated by Django 4.0.6 on 2022-10-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_alter_tables_bookduration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tables',
            name='A TableID value is valid between 1 and 50',
        ),
        migrations.AddConstraint(
            model_name='tables',
            constraint=models.CheckConstraint(check=models.Q(('TableID__gte', 1), ('TableID__lt', 20)), name='A TableID value is valid between 1 and 20'),
        ),
    ]
