# Generated by Django 4.0.6 on 2022-10-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_remove_tables_a tableid value is valid between 1 and 50_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='DinerAddress',
            field=models.TextField(default='abc'),
        ),
        migrations.AddField(
            model_name='tables',
            name='DinerAge',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='tables',
            name='DinerEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tables',
            name='DinerGender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tables',
            name='DinerName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tables',
            name='DinerPhone_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tables',
            name='Guest_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tables',
            name='Guests_num',
            field=models.IntegerField(default=0),
        ),
    ]
